# Generated by Django 4.0.5 on 2022-07-12 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.TextField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LongURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(max_length=500)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shorturl')),
            ],
        ),
    ]
